apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: writer
  name: writer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: writer
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: writer
    spec:
      containers:
        - name: writer
          image: hydrosphere/hydro-serving-writer:hacked7
          imagePullPolicy: IfNotPresent
          env:
          - name: MONGO_HOST
            value: "dev-mongo-mongodb"
          - name: MONGO_PORT
            value: "27017"
          - name: MONGO_DB
            value: "hydro-serving-data-profiler"
          - name: MONGO_USER
            value: "root"
          - name: MONGO_PASS
            value: "root"
          - name: MONGO_AUTH_DB
            value: "admin"
